import type { TranscribedItem } from '../services/storage';

export function exportToTxt(item: TranscribedItem) {
    const timestamp = new Date(item.timestamp).toLocaleString();

    const lines = [
        `SpLATform - Transcription Export`,
        `================================`,
        `Date: ${timestamp}`,
        `File: ${item.filename}`,
        `ID: ${item.id}`,
        ``,
        `STEP 1: TRANSCRIPTION`,
        `---------------------`,
        `Model: ${item.provider1}`,
        `Temperature: ${item.temp1}`,
        `Prompt:`,
        item.prompt1,
        ``,
        `Result:`,
        item.result1,
        ``,
        `================================`,
        ``,
        `STEP 2: STANDARDIZATION`,
        `-----------------------`,
        `Model: ${item.provider2}`,
        `Temperature: ${item.temp2}`,
        `Prompt:`,
        item.prompt2,
        ``,
        `Result:`,
        item.result2,
        ``,
        `================================`,
        `Generated by SpLATform Web Edition`
    ];

    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    const dateStr = new Date(item.timestamp).toISOString().split('T')[0];
    const timeStr = new Date(item.timestamp).toTimeString().split(' ')[0].replace(/:/g, '-');

    link.href = url;
    link.download = `splatform_export_${dateStr}_${timeStr}.txt`;
    document.body.appendChild(link);
    link.click();

    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
